train_dataset: mini-imagenet
train_dataset_args: {split: train, augment: resize}
val_dataset: mini-imagenet
val_dataset_args: {split: train_phase_val}

model: classifier
model_args:
    encoder: resnet12-wide
    encoder_args: {}
    classifier: linear-classifier 
    classifier_args: {n_classes: 64}

batch_size: 64
max_epoch: 60
optimizer: sgd
optimizer_args: {lr: 0.05, weight_decay: 5.e-4, milestones: [50]}

save_epoch: 5
visualize_datasets: true
